#!/usr/bin/env bash
# Bash script that displays Best School 10 times
# using while loop and if statement
h=0
while [[ $h -lt 10 ]]
do
	if [[ $h -eq 9 ]];
	then
		echo "Hi"
	fi
		echo "Best School"
	((h++))
done
