#!/usr/bin/env bash
# The Bash script is used to displays numbers from 1 to 20 and
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

h=0
while (( h <= 19 ))
do
	((h++))
	case $h in
		"4") echo -e "$h\nbad luck from China";;
		"9") echo -e "$h\nbad luck from Japan";;
		"17") echo -e "$h\nbad luck from Italy";;
		*) echo $h;;
	esac
done
