#!/usr/bin/env bash
# Bash script that displays the time for 12 hours "h" and 59 minutes "m"

h=0
while (( h <= 12 ))
do
	echo "Hour: $h"
		m=1
		while (( m <= 59 ))
		do
			echo $m
			((m++))
		done
	((h++))
done
