#!/usr/bin/env bash
# Bash script that loops 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iteration

h=1
while (( h <= 10 ))
do
	if [[ "$h" == '4' ]];
	then
		echo "bad luck"
	elif [[ "$h" == '8' ]];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		((h++))
done
