#!/usr/bin/env bash
# Bash script that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# using for loop

list=$(ls)
for h in $list;
do
	echo "$h" | cut -d"-" -f2
done
